title: Lake Lemon Guest Houses
author:
  name: Sarah Baghdadi and Teal Bingham
  email: 'joe@example.com'
metadata:
    description: 'Lake Lemon Guest Houses - Vacation Rentals in Indiana'
summary:
    size: 1000
