title: Lake Lemon Guest Houses
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Daniel Bingham for Bloomington City Council District 2 2019 Election'
summary:
    size: 1000
facebook: 'https://www.facebook.com/Lake-Lemon-Guest-Houses-114437381968688/'
email: 'suragail@gmail.com'
phone: '812-322-2436'
