title: Lake Lemon Guest Houses
author:
  name: Sarah Baghdadi and Teal Bingham
  email: 'joe@example.com'
metadata:
    description: 'Lake Lemon Guest Houses - Vacation Rentals in Indiana'
summary:
    size: 1000
facebook: 'https://www.facebook.com/Lake-Lemon-Guest-Houses-114437381968688/'
email: 'suragail@gmail.com'
phone: '812-322-2436'
