title: Daniel Bingham for Bloomington City Council District 2 2019 Election
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Daniel Bingham for Bloomington City Council District 2 2019 Election'
summary:
    size: 1000
